// src/app/components/profile/aboutme-card/aboutme-card.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-aboutme-card',
  templateUrl: './aboutme-card.component.html',
  styleUrls: ['./aboutme-card.component.scss'],
})
export class AboutmeCardComponent implements OnInit {
  constructor() {}

  ngOnInit() {}
}

<ion-card>
  <ion-card-header>
    <ion-card-title>About Me</ion-card-title>
    <ion-card-subtitle>Personal Information</ion-card-subtitle>
  </ion-card-header>
  <ion-card-content>
    <ion-list class="hasIcon" lines="none">
      <ion-item>
        <ion-icon name="information-circle-outline"></ion-icon>
        <ion-textarea
          [autoGrow]="true"
          readonly="true"
          placeholder="No 'About Me' text provided yet. 💬"
          [value]="user?.aboutMe"
        ></ion-textarea>
      </ion-item>
      <ion-item>
        <ion-icon name="flag-outline"></ion-icon>
        <ion-label>
          {{ user?.country }}
          {{ getFlagEmoji(user) }}
        </ion-label>
      </ion-item>
      <ion-item>
        <ion-icon name="male-female-outline"></ion-icon>
        <ion-label>{{ gender | capitalizeFirst }}</ion-label>
      </ion-item>
      <ion-item>
        <ion-icon name="calendar-number-outline"></ion-icon>
        <ion-label>{{ getAge(user?.birthdate) }} years old</ion-label>
      </ion-item>
      <ion-item>
        <ion-icon name="time-outline"></ion-icon>
        <ion-label>
          Registered {{ lastSeenExt(user?.$createdAt) }} ago
        </ion-label>
      </ion-item>
      <ion-item>
        <ion-icon name="at-outline"></ion-icon>
        <ion-label> &#64;{{ user?.username }} </ion-label>
      </ion-item>
      <ion-item *ngIf="account && account.emailVerification">
        <ion-icon name="shield-checkmark-outline" color="success"></ion-icon>
        <ion-label> Verified Email </ion-label>
      </ion-item>
      <ion-item *ngIf="account && !account.emailVerification">
        <ion-icon name="shield-outline" color="danger"></ion-icon>
        <ion-label> Unverified User </ion-label>
        <ion-button (click)="getAccountPage()" size="small" fill="clear">
          Edit
        </ion-button>
      </ion-item>
    </ion-list>
  </ion-card-content>
</ion-card>

// components/profile/AboutMeCard.tsx
import React from "react";
import { StyleSheet, View, Text, TextInput, Pressable } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import { getFlagEmoji, getAge, lastSeenExt } from "@/constants/utils";
import { Colors } from "@/constants/Colors";

const mockUser = {
  aboutMe: "I love coding, traveling, and learning new languages.",
  country: "US",
  gender: "male",
  birthdate: "1990-01-01",
  $createdAt: "2020-01-01T00:00:00Z",
};

const AboutMeCard = ({ user, account }) => {
  return (
    <View style={styles.card}>
      <View style={styles.cardHeader}>
        <Text style={styles.cardTitle}>About Me</Text>
        <Text style={styles.cardSubtitle}>Personal Information</Text>
      </View>
      <View style={styles.cardContent}>
        <View style={styles.item}>
          <Ionicons name="information-circle-outline" style={styles.icon} />
          <TextInput
            style={styles.textarea}
            multiline
            numberOfLines={4}
            editable={false}
            placeholder="No 'About Me' text provided yet. 💬"
            value={user.aboutMe}
          />
        </View>
        <View style={styles.item}>
          <Ionicons name="flag-outline" style={styles.icon} />
          <Text style={styles.label}>
            {user.country} {getFlagEmoji(user.country)}
          </Text>
        </View>
        <View style={styles.item}>
          <Ionicons name="male-female-outline" style={styles.icon} />
          <Text style={styles.label}>
            {user.gender.charAt(0).toUpperCase() + user.gender.slice(1)}
          </Text>
        </View>
        <View style={styles.item}>
          <Ionicons name="calendar-number-outline" style={styles.icon} />
          <Text style={styles.label}>{getAge(user.birthdate)} years old</Text>
        </View>
        <View style={styles.item}>
          <Ionicons name="time-outline" style={styles.icon} />
          <Text style={styles.label}>
            Registered {lastSeenExt(user.$createdAt)} ago
          </Text>
        </View>
        <View style={styles.item}>
          <Ionicons name="at-outline" style={styles.icon} />
          <Text style={styles.label}>@{user.username}</Text>
        </View>
        {account && account.emailVerification ? (
          <View style={styles.item}>
            <Ionicons
              name="shield-checkmark-outline"
              style={[styles.icon, { color: Colors.light.success }]}
            />
            <Text style={styles.label}>Verified Email</Text>
          </View>
        ) : (
          <View style={styles.item}>
            <Ionicons
              name="shield-outline"
              style={[styles.icon, { color: Colors.light.error }]}
            />
            <Text style={styles.label}>Unverified User</Text>
            <Pressable
              style={styles.editButton}
              onPress={() => console.log("Edit Account")}
            >
              <Text style={styles.editButtonText}>Edit</Text>
            </Pressable>
          </View>
        )}
      </View>
    </View>
  );
};

export default AboutMeCard;

const styles = StyleSheet.create({
  card: {
    borderRadius: 10,
    overflow: "hidden",
    margin: 10,
    borderWidth: 1,
    borderColor: "#ddd",
    backgroundColor: "#fff",
  },
  cardHeader: {
    padding: 20,
    alignItems: "center",
  },
  cardTitle: {
    fontSize: 24,
    fontWeight: "bold",
    textAlign: "center",
  },
  cardSubtitle: {
    fontSize: 16,
    textAlign: "center",
    color: "#555",
  },
  cardContent: {
    padding: 20,
  },
  item: {
    flexDirection: "row",
    alignItems: "center",
    marginVertical: 10,
  },
  icon: {
    fontSize: 24,
    marginRight: 20,
    color: Colors.light.primary,
  },
  label: {
    fontSize: 16,
    color: "#555",
  },
  textarea: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 5,
    padding: 10,
    backgroundColor: "#f9f9f9",
    color: "#555",
  },
  editButton: {
    marginLeft: 10,
  },
  editButtonText: {
    color: Colors.light.primary,
    fontSize: 14,
  },
});
